### ISSUE TITLE
下标越界

### ISSUE THREAD

**Issue by ghost** [burgessjp/GetWordTextView#1]
java.lang.StringIndexOutOfBoundsException: length=24; index=-1
                                                                                  at java.lang.String.substring(String.java:1926)
                                                                                  at android.text.SpannableStringInternal.<init>(SpannableStringInternal.java:33)
                                                                                  at android.text.SpannableString.<init>(SpannableString.java:34)
                                                                                  at android.text.SpannableString.subSequence(SpannableString.java:54)
                                                                                  at me.solidev.library.GetWordTextView$1.onClick(GetWordTextView.java:143)
                                                                                  at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
                                                                                  at android.widget.TextView.onTouchEvent(TextView.java:8485)
                                                                                  at android.view.View.dispatchTouchEvent(View.java:10023)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
                                                                                  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
                                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                                                  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                                  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
                                                                                  at android.view.View.dispatchPointerEvent(View.java:10243)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                                                                                  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6246)
                                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6220)
                                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6181)
                                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
                                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                  at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                  at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by burgessjp** [comment]
能提供一下你的内容吗？

**Comment by ghost** [comment]
就运行你的文件来着

**Comment by burgessjp** [comment]
不应该吧 ，我刚又运行了一次，完全正常的，你看看你的代码是不是最新的
